name: override_pod

packages:
  - packages/**
  - examples/**

ide:
  intellij: false

command:
  clean:
    hooks:
      post:
        run: melos exec -- flutter clean
        description: flutter clean

scripts:
  get:
    run: melos exec -- flutter pub get && melos gen
    description: flutter pub get && melos gen
