name: override_pod

packages:
  - packages/**
  - examples/**

ide:
  intellij: false

command:
  bootstrap:
    hooks:
      post:
        run: melos gen
        description: melos gen

  clean:
    hooks:
      post:
        run: melos exec -- flutter clean
        description: flutter clean

scripts:
  get:
    run: melos exec -- flutter pub get
    description: flutter pub get

  gen:
    run: melos gen:all --no-select

  gen:all:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 8
    packageFilters:
      dependsOn: build_runner

  test:
    run: melos test:all --no-select

  test:all:
    run: dart run build_runner build --delete-conflicting-outputs && flutter test --update-goldens --coverage && rm test/pods.gen.dart
    exec:
      concurrency: 8
    packageFilters:
      dirExists:
        - test
