builders:
  override_pod_generator:
    import: "package:override_pod_generator/builder.dart"
    builder_factories: ["overridePodsBuilder"]
    build_extensions: { "$lib$": [".dart"] }
    auto_apply: dependents
    build_to: source
