name: override_pod_generator
description: Override Pod generator for riverpod.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  override_pod_annotation: ^0.0.1
  meta: ^1.15.0
  build: ^2.4.1
  source_gen: ^1.5.0
  path: ^1.8.3
  glob: ^2.1.2
  code_builder: ^4.10.0
  dart_style: ^2.3.6

dev_dependencies:
  test:
  riverpod:
  riverpod_annotation:
  riverpod_generator:
  build_runner:
  very_good_analysis: ^5.1.0
