name: gateway
description: Gateway for infrastructure Layer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  usecase:
  override_pod_annotation:

dev_dependencies:
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  override_pod_generator:
