name: app
description: Application

version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.2
  usecase:
  gateway:

dev_dependencies:
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
